KIA_payment/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from test_app import views as test_app_views
from KIA_services import views as kia_services_views
from django.contrib.auth import views as auth_views
from KIA_auth import views as KIA_auth_views
from KIA_general import views as KIA_gen_views
from KIA_admin import views as KIA_admin_views
from KIA_notification import views as KIA_notif_views

urlpatterns = [
    path('', KIA_auth_views.redirect_to_home, name='home'),
    path('accounts/profile/', RedirectView.as_view(pattern_name='home')),
    # general
    path('contact_us/', KIA_gen_views.contact_us, name='contact_us'),
    path('about/', KIA_gen_views.about, name='about'),
    path('404/', KIA_gen_views.not_found, name='not_found'),
    path('not_authorized/', KIA_gen_views.not_authorized, name='not_authorized'),
    path('access_denied/', KIA_gen_views.access_denied, name='access_denied'),
    path('user_restricted/', KIA_gen_views.user_restricted, name='user_restricted'),
    path('purchase/', KIA_gen_views.purchase, name='purchase'),
    path('currency_rates/', KIA_gen_views.currency_rates, name='currency_rates'),
    path('FAQ/', KIA_gen_views.faq, name='faq'),
    path('add_feature/', test_app_views.add_feature, name='add_feature'),
    path('currency_exchange/', test_app_views.currency_exchange, name='currency_exchange'),
    path('send_email/', KIA_notif_views.send_email_by_employee, name='send_email_by_employee'),

    # admin
    path('admin/panel', KIA_admin_views.panel, name='admin_panel'),
    # path('admin/users_activities', KIA_admin_views.users_activities, name='users_activities'),
    # path('admin/employees_activities', KIA_admin_views.employees_activities, name='employees_activities'),
    path('admin/activities', KIA_admin_views.activities, name='activities'),
    path('admin/transactions/<int:index>/', kia_services_views.admin_transaction, name='admin_transaction'),
    path('admin/my_history', KIA_admin_views.my_history, name='my_history'),
    path('admin/financial_account_details', KIA_admin_views.financial_account_details,
         name='financial_account_details'),
    path('admin/add_system_credit', KIA_admin_views.add_system_credit, name='add_system_credit'),
    path('admin/restrict_user', KIA_admin_views.restrict_user, name='restrict_user'),
    # path('admin/restrict_user/success', KIA_admin_views.restrict_user_success, name='restrict_user_success'),
    path('admin/remove_user_restriction', KIA_admin_views.remove_user_restriction, name='remove_user_restriction'),
    # path('admin/add_transaction/', KIA_admin_views.add_transaction, name='add_transaction'),
    path('admin/add_user', KIA_admin_views.add_user, name='add_user'),
    path('admin/show_system_transactions', KIA_admin_views.show_system_transactions, name='show_system_transactions'),

    path('admin/panel', test_app_views.admin_panel, name='admin_panel'),
    path('admin/restrict_user', test_app_views.admin_restrict_user, name='admin_restrict_user'),
    path('add_transaction/', test_app_views.add_transaction, name='add_transaction'),
    # TODO: must be here or in services?
    path('admin/services/', kia_services_views.AdminServiceListDispatchView.as_view(), name='admin_service_list'),
    path('admin/services/<str:name>', kia_services_views.admin_service, name='admin_service'),
    path('admin/services/<str:name>/fields', kia_services_views.admin_service_fields, name='admin_service_fields'),
    path('admin/services/<str:name>/delete/success'
         , kia_services_views.admin_service_delete_success
         , name='admin_service_delete_success'),
    # auth
    # TODO what is the user is already logged in?
    path('login/', auth_views.login, {'template_name': 'KIA_auth/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'KIA_auth/logout.html'}, name='logout'),
    path('signup/', KIA_auth_views.sign_up, name='signup'),
    # user panel
    path('user_panel/', KIA_auth_views.user_panel, name='edit_profile'),
    path('edit_profile/', KIA_auth_views.edit_profile, name='edit_profile'),
    path('change_password/', KIA_auth_views.change_password, name='change_password'),
    path('add_credit/', KIA_auth_views.add_credit, name='add_credit'),
    path('withdraw_credit/', KIA_auth_views.withdraw_credit, name='withdraw_credit'),
    path('anonymous_transfer/', KIA_auth_views.anonymous_transfer, name='anonymous_transfer'),
    path('transactions/', KIA_auth_views.transaction_history, name='transaction_history'),
    path('transactions/<int:index>/', KIA_auth_views.transaction, name='transaction_history'),

    path('admin/', admin.site.urls),
    # user
    path('user_profile/', test_app_views.user_profile, name='user_profile'),
    path('user_transactions/', test_app_views.user_transactions, name='user_transactions'),
    path('user_wallet/', test_app_views.user_wallet, name='user_wallet'),
    path('services/physical_mastercard/', test_app_views.physical_mastercard, name='physical_mastercard'),
    path('return_money/', test_app_views.return_money, name='return_money'),
    path('anonymous_money/', test_app_views.anonymous_money, name='anonymous_money'),
    # employee
    path('all_transactions/', test_app_views.all_transactions, name='all_transactions'),
    # TODO converted to:
    path('emp/panel/', kia_services_views.emp_panel, name='emp_panel'),
    path('emp/transactions/', kia_services_views.EmpTransactionListDispatchView.as_view(), name='emp_transactions'),
    path('all_transactions/1234', test_app_views.sample_transaction, name='sample_transaction'),
    # TODO converted to:
    path('emp/transactions/<int:index>/', kia_services_views.emp_transaction, name='emp_transaction'),
    path('emp/transactions/<int:index>/take/success/',
         kia_services_views.emp_transaction_take_success,
         name='emp_transaction_take'),
    path('emp/transactions/<int:index>/report/success/',
         kia_services_views.emp_transaction_report_success,
         name='emp_transaction_report'),
    path('emp/transactions/<int:index>/finish/success/',
         kia_services_views.emp_transaction_finish_success,
         name='emp_transaction_finish'),
    path('emp/transactions/<int:index>/fail/success/',
         kia_services_views.emp_transaction_fail_success,
         name='emp_transaction_fail'),
    path('emp/taken_transactions', kia_services_views.emp_taken_transactions, name='emp_taken_transactions'),
    path('send_email/', test_app_views.send_email, name='send_email'),
    # homepage
    path('homepage/', kia_services_views.HomeListView.as_view(), name='homepage'),
    # KIA_services
    path('services/<str:name>/', kia_services_views.services, name='services'),
    path('services/<str:name>/success', kia_services_views.services_success, name='services_success'),
    path('create_service/', kia_services_views.create_service, name='service_creation'),
    path('create_service/<str:name>/', kia_services_views.create_service_cont, name='create_service_cont'),
    path('create_service/<str:name>/success', kia_services_views.create_service_success, name='create_service_success'),
    path('services/', kia_services_views.ServiceListView.as_view(), name='service_list'),
    # tinymce
    # re_path(r'^tinymce/', include('tinymce.urls'))
]

test_app/urls.py
from django.urls import path
from . import views

urlpatterns = [

]

KIA_services/models.py
from enum import Enum

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from jsonfield import JSONField


# Create your models here.
from KIA_auth.models import Profile


class KIAService(models.Model):
    dollar = 1
    euro = 2
    pound = 3
    CURRENCY_CHOICES = (
        (dollar, "دلار"),
        (euro, "یورو"),
        (pound, "پوند"),
    )

    name = models.CharField(max_length=100)
    label = models.CharField(max_length=100, null=True)
    currency = models.IntegerField(choices=CURRENCY_CHOICES, default=dollar)
    variable_price = models.BooleanField(default=False)
    price = models.IntegerField(null=True)
    commission = models.IntegerField(default=0
                                     , validators=[MaxValueValidator(100), MinValueValidator(0)])
    # TODO: let user insert html for details
    details = models.TextField()
    image_url = models.URLField(null=True)

    def __str__(self):
        return self.name


class KIAServiceField(models.Model):
    # boolean_field = 1
    char_field = 2
    choice_field = 3
    # cost_field = 4
    date_field = 5
    date_time_field = 6
    decimal_field = 7
    email_field = 9
    file_field = 10
    integer_field = 13
    multiple_choice_field = 14
    TYPE_CHOICES = (
        # (boolean_field, "فیلد صحیح و غلط"),
        (char_field, "فیلد متنی"),
        (choice_field, "فیلد انتخاب یک گزینه"),
        # (cost_field, "مبلغ ارزی"),
        (date_field, "فیلد تاریخ"),
        (date_time_field, "فیلد تاریخ و زمان"),
        (decimal_field, "فیلد عدد اعشاری"),
        (email_field, "فیلد ایمیل"),
        (file_field, "فیلد فایل"),
        (integer_field, "فیلد عدد صحیح"),
        (multiple_choice_field, "فیلد انتخاب چند گزینه"),
    )

    service = models.ForeignKey(KIAService, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, null=True)
    label = models.CharField(max_length=100)
    type = models.IntegerField(choices=TYPE_CHOICES)
    optional = models.BooleanField(default=False)
    args = JSONField(null=True)

    def __str__(self):
        return format("%s: %s" % (self.service.name, self.name))


class KIATransaction(models.Model):
    registered = 1
    being_done = 2
    done = 3
    failed = 4
    suspicious = 5
    STATE_CHOICES = (
        (registered, "ثبت شده"),
        (being_done, "در حال انجام"),
        (done, "تمام شده"),
        (failed, "رد شده"),
        (suspicious, "مشکوک"),
    )

    service = models.ForeignKey(KIAService, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='user_transactions')
    state = models.IntegerField(choices=STATE_CHOICES)
    # TODO: remove null=True from below
    register_time = models.DateTimeField(null=True)
    cost_in_currency = models.IntegerField(null=True)
    cost_in_rial = models.IntegerField(null=True)

    assigned_emp = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='emp_transactions')
    data = JSONField()

    def initialize(self, service):
        self.state = self.registered
        self.service = service

    def return_money(self):
        self.user.credit += self.cost_in_rial

KIA_services/forms.py
import json

from django import forms

from KIA_services.models import KIAServiceField, KIAService


def get_form_field(service_field):
    if service_field.type == KIAServiceField.char_field:
        if service_field.optional:
            return forms.CharField(max_length=100, label=service_field.label, required=False)
        else:
            return forms.CharField(max_length=100, label=service_field.label, required=True)

    # elif service_field.type == KIAServiceField.boolean_field:
    #     if service_field.optional:
    #         forms.CharField(label=service_field.label, required=False)
    #     else:
    #         return forms.CharField(label=service_field.label, required=True)

    elif service_field.type == KIAServiceField.choice_field:
        args = service_field.args
        choices = []
        for choice in args:
            choices.append((choice, args[choice]))

        if service_field.optional:
            return forms.ChoiceField(label=service_field.label, choices=choices, required=False)
        else:
            return forms.ChoiceField(label=service_field.label, choices=choices, required=True)

    elif service_field.type == KIAServiceField.date_field:
        if service_field.optional:
            return forms.DateField(label=service_field.label, required=False)
        else:
            return forms.DateField(label=service_field.label, required=True)

    elif service_field.type == KIAServiceField.date_time_field:
        if service_field.optional:
            return forms.DateTimeField(label=service_field.label, required=False)
        else:
            return forms.DateTimeField(label=service_field.label, required=True)

    elif service_field.type == KIAServiceField.decimal_field:
        if service_field.optional:
            return forms.DecimalField(label=service_field.label, required=False)
        else:
            return forms.DecimalField(label=service_field.label, required=True)

    elif service_field.type == KIAServiceField.email_field:
        if service_field.optional:
            return forms.EmailField(label=service_field.label, required=False)
        else:
            return forms.EmailField(label=service_field.label, required=True)

    elif service_field.type == KIAServiceField.file_field:
        if service_field.optional:
            return forms.FileField(label=service_field.label, required=False)
        else:
            return forms.FileField(label=service_field.label, required=True)

    elif service_field.type == KIAServiceField.integer_field:
        if service_field.optional:
            return forms.IntegerField(label=service_field.label, required=False)
        else:
            return forms.IntegerField(label=service_field.label, required=True)

    elif service_field.type == KIAServiceField.multiple_choice_field:
        # args = json.loads(service_field.args)
        args = service_field.args
        choices = []
        for choice in args:
            choices.append((choice, args[choice]))

        if service_field.optional:
            return forms.MultipleChoiceField(label=service_field.label, choices=choices, required=False)
        else:
            return forms.MultipleChoiceField(label=service_field.label, choices=choices, required=True)


def date_handler(obj):
    return obj.isoformat() if hasattr(obj, 'isoformat') else obj


class KIAServiceForm(forms.Form):
    def __init__(self, service, *args, **kwargs):
        super(KIAServiceForm, self).__init__(*args, **kwargs)
        service_fields = service.kiaservicefield_set.all()
        for service_field in service_fields:
            self.fields[service_field.name] = get_form_field(service_field)

    def get_json_data(self):
        data = self.cleaned_data
        json_string = json.dumps(data, default=date_handler)
        return json_string


class KIAServiceCreationForm(forms.ModelForm):
    price = forms.IntegerField(label='قیمت', required=False)

    class Meta:
        model = KIAService
        fields = ('name', 'label', 'currency', 'variable_price', 'price', 'commission', 'details', 'image_url')
        labels = {
            'name': 'نام انگلیسی خدمت',
            'label': 'نام فارسی خدمت',
            'currency': 'ارز',
            'variable_price': 'قیمت متغیر',
            'price': 'قیمت',
            'details': 'توضیحات خدمت',
            'image_url': 'آدرس عکس خدمت',
            'commission': 'درصد کارمزد(به صورت یک عدد از ۰ تا ۱۰۰)'
        }


class KIAServiceFieldCreationForm(forms.ModelForm):
    class Meta:
        model = KIAServiceField
        fields = ('name', 'label', 'type', 'optional', 'args')
        labels = {
            'name': 'نام انگلیسی فیلد',
            'label': 'نام فارسی فیلد(برای نمایش به کاربر)',
            'type': 'نوع فیلد',
            'optional': 'اختیاری بودن یا نبودن فیلد',
            'args': 'گزینه‌های فیلد',
        }

templates/KIA_services/admin_transaction.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#  <meta charset="UTF-8">#}
{#  <title>Transaction</title>#}
{#</head>#}
{#<body>#}
{#<ul>#}
{#  <li>نام خدمت: {{ transaction.service.name }}</li>#}
{#  <li>نام کاربر: {{ transaction.user.username }}</li>#}
{#  <li>وضعیت درخواست: {{ transaction.state }}</li>#}
{#  <li>اطلاعات درخواست:#}
{#    {% for key, values in data.items %}#}
{#      <ul>#}
{#        <li>{{ key }} : {{ values }}</li>#}
{#      </ul>#}
{#    {% endfor %}#}
{#  </li>#}
{#</ul>#}
{#<form action="" method="post" novalidate>#}
{#  {% csrf_token %}#}
{#  <input type="submit" name="cont" value="انجام خدمت">#}
{#  <input type="submit" name="finish" value="پایان ساخت خدمت">#}
{#</form>#}
{#</body>#}
{#</html>#}


{% extends "master.html" %}

{% block content %}
  <head>
    <link rel="stylesheet" href="/static/Panels.css">
  </head>

  <div id="wrapper" class="row" style="padding-bottom:20px;">

    <div id="sidebar-wrapper" class="col-3" align="center" style="padding-right: 50px;">
      <div class="list-group">
        <a href="/admin/panel" class="list-group-item list-group-item-action">پنل مدیر</a>
        {#        <a href="/admin/users_activities" class="list-group-item list-group-item-action active">فعالیت کاربران</a>#}
        {#        <a href="/admin/employees_activities" class="list-group-item list-group-item-action">فعالیت کارمندان</a>#}
        <a href="/admin/activities" class="list-group-item list-group-item-action active">فعالیت‌ها</a>
        <a href="/admin/my_history" class="list-group-item list-group-item-action">سابقهٔ من</a>
        <a href="/admin/financial_account_details" class="list-group-item list-group-item-action">جزئیات حساب مالی</a>

        <a href="/admin/restrict_user" class="list-group-item list-group-item-action">محدود کردن کاربر</a>
        <a href="/admin/remove_user_restriction" class="list-group-item list-group-item-action">رفع محدودیت</a>
        <a href="/admin/add_system_credit" class="list-group-item list-group-item-action ">اضافه کردن اعتبار</a>
        <a href="/create_service" class="list-group-item list-group-item-action">اضافه کردن تراکنش</a>
        <a href="/admin/services" class="list-group-item list-group-item-action">مشاهده و بررسی سرویس‌ها</a>
        <a href="/admin/add_user" class="list-group-item list-group-item-action">اضافه کردن کاربر</a>
      </div>
    </div>

    <div id="page-content-wrapper" class="col-9" align="center" style="padding-left: 50px; padding-right: 50px">
      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">نام خدمت</div>
        <div class="col-6">{{ transaction.service.name }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">نام کاربر</div>
        <div class="col-6">{{ transaction.user }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">وضعیت درخواست</div>
        <div class="col-6">{{ transaction.get_state_display }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">کارمند در حال کار</div>
        <div class="col-6">{{ transaction.assigned_emp }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">زمان ثبت</div>
        <div class="col-6">{{ transaction.register_time }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">قیمت ریالی</div>
        <div class="col-6">{{ transaction.cost_in_rial }}</div>
        <div class="col-2"></div>
      </div>

      {% for key, value in data.items %}
        <div class="row" align="center">
          <div class="col-2"></div>
          <div class="col-2">{{ key }}</div>
          <div class="col-6">{{ value }}</div>
          <div class="col-2"></div>
        </div>
      {% endfor %}

      <form action="" method="post" novalidate>
        {% csrf_token %}
        {% if transaction.state == transaction.suspicious %}

          <input type="submit" name="fail" value="رد درخواست" class="btn btn-primary">
          <input type="submit" name="return" value="رفع مشکوکی!" class="btn btn-primary">
          {##}
          {#        {% elif transaction.state == transaction.being_done %}#}
          {#          {% if transaction.assigned_emp == user %}#}
          {#            <input type="submit" name="finish" value="اتمام درخواست" class="btn btn-primary">#}
          {#            <input type="submit" name="report" value="گزارش مورد مشکوک" class="btn btn-primary">#}
          {#            <input type="submit" name="fail" value="رد کردن درخواست" class="btn btn-primary">#}
          {#          {% endif %}#}
        {% endif %}
        <button type="button" onclick="javascript:history.back()" class="btn btn-primary">
          بازگشت
        </button>
      </form>

    </div>

  </div>

{% endblock content %}

templates/KIA_services/create_service.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#  <meta charset="UTF-8">#}
{#  <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<form action="" method="post" novalidate>#}
{#  <table>#}
{#    {{ form.as_table }}#}
{#  </table>#}
{#  {% csrf_token %}#}
{#  <input type="submit" value="ادامه ساخت خدمت">#}
{#</form>#}
{#</body>#}
{#</html>#}
<head>
  <style>
    #id_name {
      direction: ltr;
    }
  </style>
</head>
{% extends "master.html" %}

{% block content %}
  <head>
    <link rel="stylesheet" href="/static/Panels.css">
  </head>

  <div id="wrapper" class="row" style="padding-bottom:20px;">

    <!-- Sidebar -->
    <div id="sidebar-wrapper" class="col-3" align="center" style="padding-right: 50px;">
      <div class="list-group">
        <a href="/admin/panel" class="list-group-item list-group-item-action">پنل مدیر</a>
        {#        <a href="/admin/users_activities" class="list-group-item list-group-item-action">فعالیت کاربران</a>#}
        {#        <a href="/admin/employees_activities" class="list-group-item list-group-item-action">فعالیت کارمندان</a>#}
        <a href="/admin/activities" class="list-group-item list-group-item-action">فعالیت‌ها</a>
        <a href="/admin/my_history" class="list-group-item list-group-item-action">سابقهٔ من</a>
        <a href="/admin/restrict_user" class="list-group-item list-group-item-action">محدود کردن کاربر</a>
        <a href="/admin/remove_user_restriction" class="list-group-item list-group-item-action">رفع محدودیت</a>
        <a href="/admin/add_system_credit" class="list-group-item list-group-item-action">اضافه کردن اعتبار</a>
        {#        <a href="/admin/add_transaction" class="list-group-item list-group-item-action active">اضافه کردن تراکنش</a>#}
        <a href="/create_service" class="list-group-item list-group-item-action active">اضافه کردن تراکنش</a>
        <a href="/admin/services" class="list-group-item list-group-item-action">مشاهده و بررسی سرویس‌ها</a>
        <a href="/admin/add_user" class="list-group-item list-group-item-action">اضافه کردن کاربر</a>
      </div>
    </div>

    <div id="page-content-wrapper" class="col-9" align="center" style="padding-left: 50px; padding-right: 50px">
      {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <ul>
            <strong>خطاهای زیر پیش آمده:</strong>
            {{ form.non_field_errors }}
            {% for field in form %}
              {% if field.errors %}
                <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
            {% endfor %}
          </ul>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}

      <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group row" align="right">
          <h3 class="col-sm-5">اضافه کردن تراکنش جدید</h3>
        </div>

        {% for item in form %}
          {#                        {{ item.label_tag }}{{ item }}#}
          <div class="form-group row">
            <div class="col-sm-4 col-form-label text-md-right">
              {{ item.label_tag }}
            </div>
            <div class="col-md-6">
              {{ item }}
            </div>
          </div>
        {% endfor %}


        <div style="padding-left: 150px">
          <button type="submit" name="submit" class="btn btn-primary">ادامهٔ ساخت خدمت</button>
          {#          <input type="submit" class="btn btn-primary" value="ادامه ساخت خدمت">#}
        </div>

      </form>
    </div>

  </div>

  <script>
      window.onload = function () {
          let checkbox = document.getElementById("id_variable_price");
          let input = document.getElementById("id_price");
          let oldVar = 0;
          checkbox.onchange = function () {
              if (checkbox.checked) {
                  input.disabled = true;
                  oldVar = input.value;
                  input.value = 0;
              }
              else {
                  document.getElementById("id_price").disabled = false;
                  input.value = oldVar;
              }
          };
      }
  </script>

  <script src="/static/Translator.js"></script>
  <script src="/static/MakeInputsCute.js"></script>
{% endblock content %}

templates/KIA_services/create_service_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    سرویس {{ service_name }} با موفقیت ساخته شد!
</body>
</html>

templates/KIA_services/transaction.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#  <meta charset="UTF-8">#}
{#  <title>Transaction</title>#}
{#</head>#}
{#<body>#}
{#<ul>#}
{#  <li>نام خدمت: {{ transaction.service.name }}</li>#}
{#  <li>نام کاربر: {{ transaction.user.username }}</li>#}
{#  <li>وضعیت درخواست: {{ transaction.state }}</li>#}
{#  <li>اطلاعات درخواست:#}
{#    {% for key, values in data.items %}#}
{#      <ul>#}
{#        <li>{{ key }} : {{ values }}</li>#}
{#      </ul>#}
{#    {% endfor %}#}
{#  </li>#}
{#</ul>#}
{#<form action="" method="post" novalidate>#}
{#  {% csrf_token %}#}
{#  <input type="submit" name="cont" value="انجام خدمت">#}
{#  <input type="submit" name="finish" value="پایان ساخت خدمت">#}
{#</form>#}
{#</body>#}
{#</html>#}


{% extends "master.html" %}

{% block content %}
  <head>
    <link rel="stylesheet" href="/static/Panels.css">
  </head>

  <div id="wrapper" class="row" style="padding-bottom:20px;">

    <div id="sidebar-wrapper" class="col-3" align="center" style="padding-right: 50px;">
      <div class="list-group">
        <a href="/user_panel" class="list-group-item list-group-item-action">پنل کاربری</a>
        <a href="/edit_profile" class="list-group-item list-group-item-action">ویرایش پروفایل</a>
        <a href="/change_password" class="list-group-item list-group-item-action">تغییر رمز عبور</a>
        <a href="/add_credit" class="list-group-item list-group-item-action">اضافه کردن اعتبار</a>
        <a href="/withdraw_credit" class="list-group-item list-group-item-action">برداشت پول از اعتبار</a>
        <a href="/anonymous_transfer" class="list-group-item list-group-item-action">پرداخت ناشناس</a>
        <a href="/transactions" class="list-group-item list-group-item-action active">تاریخچهٔ تراکنش‌ها</a>
      </div>
    </div>

    <div id="page-content-wrapper" class="col-9" align="center" style="padding-left: 50px; padding-right: 50px">
      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">نام خدمت</div>
        <div class="col-6">{{ transaction.service.name }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">نام کاربر</div>
        <div class="col-6">{{ transaction.user }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">وضعیت درخواست</div>
        <div class="col-6">{{ transaction.get_state_display }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">زمان ثبت</div>
        <div class="col-6">{{ transaction.register_time }}</div>
        <div class="col-2"></div>
      </div>

      <div class="row" align="center">
        <div class="col-2"></div>
        <div class="col-2">قیمت ریالی</div>
        <div class="col-6">{{ transaction.cost_in_rial }}</div>
        <div class="col-2"></div>
      </div>

      {% for key, value in data.items %}
        <div class="row" align="center">
          <div class="col-2"></div>
          <div class="col-2">{{ key }}</div>
          <div class="col-6">{{ value }}</div>
          <div class="col-2"></div>
        </div>
      {% endfor %}

      <form action="" method="post" novalidate>
        {% csrf_token %}
        <button type="button" onclick="javascript:history.back()" class="btn btn-primary">
          بازگشت
        </button>
      </form>

    </div>

  </div>

{% endblock content %}